# Generated by Django 3.0.6 on 2020-05-08 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(default='000000', max_length=70)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=70)),
                ('device_type', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall')], default='000000', max_length=30)),
                ('platform', models.CharField(choices=[('cisco', 'ios'), ('juniper', 'junos')], default='Firewall', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('devices', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statool.Device')),
            ],
        ),
    ]
