# Generated by Django 3.0.6 on 2020-05-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmdname', models.CharField(max_length=100)),
                ('cmdformat', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('cisco', 'ios'), ('juniper', 'junos')], default='Firewall', max_length=30)),
            ],
        ),
    ]
