# Generated by Django 3.0.6 on 2020-05-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statool', '0003_auto_20200527_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commands',
            new_name='Command',
        ),
        migrations.RenameField(
            model_name='command',
            old_name='commands',
            new_name='command',
        ),
    ]
